#!/bin/sh

case "$1" in
    start)
        printf "Setting slot good\n"
        cmdline="$(cat /proc/cmdline)"
        root_dev=""

        for arg in $cmdline; do
            case "$arg" in
                root=*)
                    root_dev="${arg#root=}"
                    ;;
            esac
        done
        echo "Rootdevice is $root_dev"
        if [ "$root_dev" = "/dev/mtdblock7" ]; then
            booted_slot="a"
        else
            booted_slot="b"
        fi
        echo "Booted slot: $booted_slot"

        last_valid_slot="$(slotcfg get_slot /dev/mtd6)"
        if [ "$last_valid_slot" = "$booted_slot" ]; then
            echo "Setting good slot"
            slotcfg set_last_good_if_unknown /dev/mtd6
        fi
        ;;
    stop)
        ;;
    restart|reload)
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
